# 1D Numpy in Python
## Objectives
*   Import and use the `numpy` library
*   Perform operations with `numpy`

NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python and it is an open source project. The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

In [1]:
# import numpy library
import numpy as np 
print('Done')

Done


In [2]:
# Create a numpy array
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [3]:
# Print each element
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [4]:
print(np.__version__)

1.26.4


In [5]:
# Check the type of the array
type(a)

numpy.ndarray

In [6]:
# Check the type of the values stored in numpy array
a.dtype

dtype('int32')

In [10]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
b.dtype

dtype('float64')

### Assign value

In [14]:
# Create numpy array
c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [15]:
# Assign the first element to 100
c[0] = 100
c

array([100,   1,   2,   3,   4])

In [16]:
# Assign the 5th element to 0
c[4] = 0
c

array([100,   1,   2,   3,   0])

### Slicing
Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].The element at end index is not being included in the output.

We can select the elements from 1 to 3 and assign it to a new numpy array <code>d</code> as follows:

In [17]:
# Slicing the numpy array
d = c[1:4]
d

array([1, 2, 3])

In [18]:
# Set the fourth element and fifth element to 300 and 400
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

We can also define the steps in slicing, like this: [start:end:step].

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [21]:
print(arr[:4])

[1 2 3 4]


If we don't pass end it considers till the length of array.

In [22]:
print(arr[4:])

[5 6 7]


In [23]:
print(arr[1:5:])

[2 3 4 5]


### Try it yourself
Print the even elements in the given array.

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])

[2 4 6 8]


### Assign Value with List
Similarly, we can use a list to select more than one specific index.
The list `select` contains several values:

In [25]:
# Create the index list
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [26]:
# Use List to select elements
d = c[select]
d

array([100,   2, 300, 400])

In [27]:
# Assign the specified elements to new value
c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

### Other Attributes


In [28]:
# Create a numpy array
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [29]:
# Get the size of numpy array
a.size

5

In [30]:
# Get the number of dimensions of numpy array
a.ndim

1

The attribute <code>shape</code> is a tuple of integers indicating the size of the array in each dimension:

In [32]:
# Get the shape/size of numpy array
a.shape

(5,)

### Try it yourself
Find the size ,dimension and shape for the given array **b**

In [33]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

In [35]:
b.size

7

In [36]:
b.ndim

1

In [37]:
b.shape

(7,)