## Objectives

* Operate comfortably with `numpy`
* Perform complex operations with `numpy`

<hr>

## Create a 2D Numpy Array

In [53]:
# Import the libraries
import numpy as np

Consider the list <code>a</code>, which contains three nested lists **each of equal size**. 

In [54]:
# Create a list
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [55]:
# Convert list to Numpy Array
# Every element is the same type
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [56]:
# Show the numpy array dimensions
A.ndim

2

In [57]:
# Show the numpy array shape
A.shape

(3, 3)

In [58]:
# Show the numpy array size
A.size

9

<hr>

## Accessing different elements of a Numpy Array

We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:  

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="400">

We can access the 2nd-row, 3rd column as shown in the following figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="220">

In [59]:
# Access the element on the second row and third column
A[1, 2]

23

In [60]:
# Access the element on the second row and third column
A[1][2]

23

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="220">

In [61]:
# Access the element on the first row and first and second columns
A[0][0:2]

array([11, 12])

Corresponding to the following figure: 

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="220"><br />

In [62]:
# Access the element on the first and second rows and third column
A[0:2, 2]

array([13, 23])

<hr>

# Basic Operations

We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="350">

In [63]:
# Create a numpy array X
X = np.array([[1, 0], [0, 1]]) 

In [64]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 

In [65]:
# Add X and Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

<h3>Multiplying</h3>
A numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="350">

In [66]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 

In [67]:
# Multiply Y with 2
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="350">

In [68]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 

In [69]:
# Create a numpy array X
X = np.array([[1, 0], [0, 1]]) 

In [70]:
# Multiply X with Y
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:

In [71]:
# Create a matrix A
A = np.array([[0, 1, 1], [1, 0, 1]])

In [72]:
# Create a matrix B
B = np.array([[1, 1], [1, 1], [-1, 1]])

In [73]:
# Calculate the dot product
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [74]:
# Calculate the sine of Z
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the numpy attribute <code>T</code> to calculate the transposed matrix

In [75]:
# Create a matrix C
C = np.array([[1,1],[2,2],[3,3]])

In [76]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])

<h2>Quiz on 2D Numpy Array</h2>

Consider the following list <code>a</code>, convert it to Numpy Array. 

In [77]:
# Write your code below and press Shift+Enter to execute
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [78]:
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
#array size
A.size

12

In [80]:
#Access the element on the first row and first and second columns.
A[0][0:2]

array([1, 2])

Perform matrix multiplication with the numpy arrays A and B

In [81]:
# Write your code below and press Shift+Enter to execute
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [82]:
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])